version: "3.6"
services:
    mongo:
        container_name: mongo
        image: mongo
        volumes:
            - ./data:/data/db
        ports:
            - "27017:27017"
    ide:
        container_name: codecompileride
        image: satheesh1997/codecompileride
        restart: always
        build: .
        environment:
            - MONGO_DB_URL=mongodb://mongo:27017
        volumes:
            - ./src:/src/
            - /src/node_modules
        ports:
            - "8000:8000"
        command: npm run develop
        depends_on:
            - mongo
